name: crone job

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js and cache
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run batch
        run: node --loader ts-node/esm ./batch/index.ts
        env:
          VITE_SUPABASE_URL: ${{secrets.VITE_SUPABASE_URL}}
          VITE_SUPABASE_ANON_KEY: ${{secrets.VITE_SUPABASE_ANON_KEY}} 
      # - name: Run batch
      #   run: npx ts-node --project tsconfig.node.json ./batch/index.ts